local cors = require "cors"
describe("test CORS header helpers", function()
  it("domain whitelist detect proper origin domains", function()
    assert.are.same(true, cors.origin_matches_whitelist("http://wikia.com"))
    assert.are.same(true, cors.origin_matches_whitelist("http://stargate.test.wikia.com"))
    assert.are.same(true, cors.origin_matches_whitelist("https://stargate.test.wikia.com"))
    assert.are.same(true, cors.origin_matches_whitelist("https://stargate.test.wikia-dev.com"))
    assert.are.same(true, cors.origin_matches_whitelist("http://wikia-dev.com"))
    assert.are.same(false, cors.origin_matches_whitelist("http://wikia-inc.com"))
    assert.are.same(false, cors.origin_matches_whitelist("http://one.wikia-inc.com"))
    assert.are.same(false, cors.origin_matches_whitelist("http://google.com"))
    assert.are.same(false, cors.origin_matches_whitelist("http://fakewebsitewikia.com"))
    assert.are.same(false, cors.origin_matches_whitelist("http://www.wikia.com.fakewebsite"))
  end)  
end)
