#!/bin/bash
# How to use this:
# 1. Add key "config/api-gateway/*" with the upstream host to
#		your consul key value store.
# 2. Run this with ./scripts/templatize your-consul-host:8500
WORKING=$(dirname $0)/..
CONSUL_URI=$1
if [[ -z $CONSUL_URI ]]; then
	echo Usage: scripts/templatize localhost:8500
	exit 1
fi

if [[ -z $WIKIA_ENVIRONMENT ]]; then
  export WIKIA_ENVIRONMENT="dev"
fi
consul-template -consul $CONSUL_URI\
  -log-level=info\
  -template "$WORKING/templates/src/config.lua:$WORKING/src/config.lua"\
	-template "$WORKING/templates/src/configured_locations.lua:$WORKING/src/configured_locations.lua"\
	-template "$WORKING/templates/conf/upstreams.conf:$WORKING/nginx/production/upstreams.conf"\
	-once
